// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission5_Higbee.Models;

namespace Mission5_Higbee.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220126211739_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission5_Higbee.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieSubmissionId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieSubmissionId = 1,
                            Category = "Family",
                            Director = "Chris Buck and Jennifer Lee",
                            Edited = false,
                            Lent_to = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Frozen",
                            Year = 2013
                        },
                        new
                        {
                            MovieSubmissionId = 2,
                            Category = "Action/Adventure",
                            Director = "Joe and Anthony Russo",
                            Edited = false,
                            Lent_to = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Captain America: The Winter Soldier",
                            Year = 2014
                        },
                        new
                        {
                            MovieSubmissionId = 3,
                            Category = "Action/Adventure",
                            Director = "Haruo Sotozaki",
                            Edited = false,
                            Lent_to = "",
                            Notes = "",
                            Rating = "R",
                            Title = "Demon Slayer: Mugen Train",
                            Year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
